import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import main_classes.Author;
import main_classes.Book;

import java.util.ArrayList;
import java.util.Date;

import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.awt.event.ActionEvent;
import javax.swing.JTable;
import javax.swing.JLabel;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usama
 */
public class Books_Add extends javax.swing.JFrame {

	private ArrayList<Author> all_Authors = Intro.bd.getAuthorsByName();
	public ArrayList<Author> new_Authors_array;
	
    /**
     * Creates new form Edit_A
     */
    public Books_Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new_Authors_array.add(all_Authors.get(all_books_list.getSelectedIndex()));        		
        		model.addElement(model2.getElementAt(all_books_list.getSelectedIndex()));
        		
        	
        	}
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jTextField1.setText("");

        jTextField2.setText("");

        jLabel1.setText("Title");

        jLabel2.setText("Page Count");

        jButton1.setText("Add Author");
        
        
        JLabel lblAuthorBooks = new JLabel();
        lblAuthorBooks.setText("Book's Authors");
        
        lblAllBooks = new JLabel();
        lblAllBooks.setText("All Authors");
        
        textField = new JTextField();
        textField.setText("");
        
        lblPublishDate = new JLabel();
        lblPublishDate.setText("Publish Date");
       
        
        list = new JList();
        list.setModel(new AbstractListModel() {
        	String[] values = new String[] {"a"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });
        
        list_1 = new JList();
        list_1.setModel(new AbstractListModel() {
        	String[] values = new String[] {"b", "c"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });

        
        
        model = new DefaultListModel<>();
        my_books_list = new JList<>( model );
        
//        for(Book book : author.books){        	
//        	model.addElement(book.getTitle());
//        }
//        
         model2 = new DefaultListModel<>();
         all_books_list =  new JList<>( model2 );
        
        
        
       for(Author author : all_Authors){        	
        	model2.addElement(author.getFirstName()+" "+author.getLastName());
        }
        
       new_Authors_array = new ArrayList<>();

      
       
     
       
//      // JScrollPane scrollPane1 = new JScrollPane(list);
//       jScrollPane1.setViewportView(list);
//       jScrollPane1.setViewportView(my_books_list);
       //Author_Edit.add(scrollPane1);
       
        
        
        
        btnNewButton = new JButton("Save");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		String s = jTextField2.getText();
        		        		
        		 if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||textField.getText().equals("")){
         			JOptionPane.showMessageDialog(null,"Please Fill All Fields");

        		 }
        		 else if(!Intro.isInteger(s))
        		 {
          			JOptionPane.showMessageDialog(null,"Please enter an integer for page count");
        		 }
        		 
        		else{
        			new_Book = new Book("title",50,"date",null);
            		new_Book.setTitle(jTextField1.getText());

            		int i_i = Integer.parseInt(s);
            		new_Book.setPageCount(i_i);
            		        		
            		new_Book.setPublishDate(textField.getText());
            		
            		for(Author a:new_Authors_array)
            			new_Book.addAuthor(a);
            			
            		Intro.bd.addBook(new_Book);
            		        		
            		int rowCount = Books.model.getRowCount();
            		for (int i = rowCount - 1; i >= 0; i--) {
            			Books.model.removeRow(i);
            		}
            		
            		Books.model = (DefaultTableModel) Books.jTable1.getModel();
            		
            		for(Book book :Intro.bd.getBooksByName())
            		Books.model.addRow(new Object[]{book.getTitle(),book.getPageCount(),book.getPublishDate()});
            		
        		}
        		
        	}
        });
        
        btnDelete = new JButton("Delete");
        btnDelete.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new_Authors_array.remove(my_books_list.getSelectedIndex());
        		//new_author.books.remove(new_author.books.get(my_books_list.getSelectedIndex()));
        		//model2.addElement(model.getElementAt(my_books_list.getSelectedIndex()));
        		model.removeElementAt(my_books_list.getSelectedIndex());
        	}
        });
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(51)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        			.addGap(62)
        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(51)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        			.addGap(37)
        			.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(51)
        			.addComponent(lblPublishDate, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        			.addGap(22)
        			.addComponent(textField, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(25)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblAuthorBooks, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        				.addComponent(my_books_list, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(28)
        							.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jButton1)
        								.addComponent(btnDelete, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE))
        							.addGap(32))
        						.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(btnNewButton)
        							.addGap(46)))
        					.addComponent(all_books_list, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        					.addGap(27)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(lblAllBooks, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
        					.addGap(18))))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(21)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(jLabel2))
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(27)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(3)
        					.addComponent(lblPublishDate))
        				.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(41)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblAuthorBooks)
        				.addComponent(lblAllBooks))
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(jButton1)
        					.addGap(27)
        					.addComponent(btnDelete)
        					.addGap(18)
        					.addComponent(btnNewButton))
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(my_books_list, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE)
        					.addComponent(all_books_list, GroupLayout.PREFERRED_SIZE, 118, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(20)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(13))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Books_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Books_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Books_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Books_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Books_Add = new Books_Add();
            	Books_Add.setVisible(true);
            }
        });
    }

    private static Books_Add  Books_Add;
    private DefaultListModel<String> model,model2;
    private Book new_Book;
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private JList list_1;
    private JList my_books_list;
    private JList all_books_list;
    private JList list;
    private JButton btnNewButton;
    private JButton btnDelete;
    private JLabel lblAllBooks;
    private JTextField textField;
    private JLabel lblPublishDate;
}
