import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.ParseException;

import main_classes.BooksDistributer;

import java.awt.event.ActionEvent;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.UIManager;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usama
 */
public class Intro extends javax.swing.JFrame {

    /**
     * Creates new form n
     */
    public Intro() {
        initComponents();
        
        
    }

    public static boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException e) {
            return false ;
        }
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	bd = new BooksDistributer();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		intro.setVisible(false);
        		 a = new Authors();
        		 a.setVisible(true);
        	}
        });
        
        jButton2 = new javax.swing.JButton();
        jButton2.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		//intro.dispose();

        		intro.setVisible(false);
        		Books b = new Books();
        		b.setVisible(true);
        	}
        });
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		intro.setVisible(false);
        		Stores s = new Stores();
        		s.setSize(800,600);
        		s.setVisible(true);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Authors");

        jButton2.setText("Books");

        jButton3.setText("Stores");
        
        JButton btnSerialize = new JButton();
        btnSerialize.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bd = bd.DeSerialize("D:\\new book distribute.bin");
        	}
        });
        btnSerialize.setText("Deserialize");
        
        JButton btnSerialize_1 = new JButton();
        
        btnSerialize_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		bd.Serialize("D:\\new book distribute.bin", bd);
    			JOptionPane.showMessageDialog(null,"Saved To D:\\new book distribute.bin");

        	}
        });
        btnSerialize_1.setText("Serialize");
        
        label = new JLabel("The Distributor");
        label.setForeground(Color.ORANGE);
        label.setFont(new Font("Tempus Sans ITC", Font.BOLD, 18));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(145, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnSerialize, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE)
        						.addComponent(btnSerialize_1, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))
        					.addGap(161))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(label, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)
        					.addGap(112))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(44)
        			.addComponent(label, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
        			.addGap(44)
        			.addComponent(jButton1)
        			.addGap(33)
        			.addComponent(jButton2)
        			.addGap(34)
        			.addComponent(jButton3)
        			.addGap(32)
        			.addComponent(btnSerialize_1)
        			.addGap(35)
        			.addComponent(btnSerialize)
        			.addContainerGap(33, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    
    class OpenL implements ActionListener {
        public void actionPerformed(ActionEvent e) {
          JFileChooser c = new JFileChooser();
          // Demonstrate "Open" dialog:
          int rVal = c.showOpenDialog(Intro.this);
          if (rVal == JFileChooser.APPROVE_OPTION) {
            filename=c.getSelectedFile().getName();
            dir=c.getCurrentDirectory().toString();
          }
          if (rVal == JFileChooser.CANCEL_OPTION) {
            filename = "You pressed cancel" ;
            dir ="";
          }
        }
      }

      class SaveL implements ActionListener {
        public void actionPerformed(ActionEvent e) {
          JFileChooser c = new JFileChooser();
          // Demonstrate "Save" dialog:
          int rVal = c.showSaveDialog(Intro.this);
          if (rVal == JFileChooser.APPROVE_OPTION) {
            filename=c.getSelectedFile().getName();
            dir=c.getCurrentDirectory().toString();
          }
          if (rVal == JFileChooser.CANCEL_OPTION) {
            filename="You pressed cancel";
            dir="";
          }
        }
      }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
                //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());


            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Intro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	intro = new Intro();
            	intro.setVisible(true);
            	
            }
        });
    }
    private String filename,dir;
	public static BooksDistributer bd;
    public static Intro intro;
    private static Authors a;
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private JLabel label;
}
