import javax.swing.GroupLayout.Alignment;

import java.util.ArrayList;

import javax.swing.DefaultCellEditor;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

import main_classes.BookData;
import main_classes.Store;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;

import java.awt.Component;
import java.awt.Font;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JTextField;



/**
 *
 * @author Usama
 */
public class Store_Edit extends javax.swing.JFrame {

	private Store s = Intro.bd.getStoresByLocation().get(Stores.sel);
	public   ArrayList<BookData> books = Intro.bd.getStoresByLocation().get(Stores.sel).BooksData;
    
	
	public static int sel;

	
    /**
     * Creates new form Edit_S
     */

    public Store_Edit() {
    	addWindowListener(new WindowAdapter() {
    		@Override
    		public void windowClosed(WindowEvent arg0) {
    			Stores.in_Stores = true;
        		Stores.in_Books = false;
        		Stores.in_Authors= false;
        		Stores.in_Store_Books = false;
    		}
    	});
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

    	Stores.in_Books = false;
    	Stores.in_Stores = false;
    	Stores.in_Authors= false;
    	Stores.in_Store_Books = true;
    	
    	
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		Store_Edit_Add_Book a_b = new Store_Edit_Add_Book();
        		a_b.setVisible(true);
        	}
        });
        jButton3 = new javax.swing.JButton();
        jButton3.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
             books.remove(books.get(sel));
             model2 = (DefaultTableModel) jTable2.getModel(); 
       	     model2.removeRow(sel);

        	}
        });
        jButton4 = new javax.swing.JButton();
        jButton4.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		
        		if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||jTextField3.getText().equals("")||jTextField4.getText().equals("")){
         			JOptionPane.showMessageDialog(null,"Please Fill All Fields");

        		}
        		else{
            	Stores.in_Books = false;
            	Stores.in_Stores = true;
            	Stores.in_Authors= false;
            	Stores.in_Store_Books = false;
        		
            	Intro.bd.getStoresByLocation().get(Stores.sel).setName(jTextField1.getText());
            	Intro.bd.getStoresByLocation().get(Stores.sel).setCity(jTextField2.getText());
            	Intro.bd.getStoresByLocation().get(Stores.sel).setCountry(jTextField3.getText());
            	Intro.bd.getStoresByLocation().get(Stores.sel).adress = jTextField4.getText();
            	
          	      Stores.model = (DefaultTableModel) Stores.jTable1.getModel();
          	      Stores.model.setValueAt(jTextField1.getText(), Stores.sel, 0);
          	      Stores.model.setValueAt(jTextField2.getText(), Stores.sel, 1);
          	      Stores.model.setValueAt(jTextField3.getText(), Stores.sel, 2);
          	      Stores.model.setValueAt(jTextField4.getText(), Stores.sel, 3);
          	     
          	      int i=0;
          	      for(BookData b : Intro.bd.getStoresByLocation().get(Stores.sel).BooksData){
          	    	  Object obj = jTable2.getValueAt(i++, 2);
          	    	  
          	    	  b.setCopies(Integer.parseInt(obj.toString()));
          	      }
          	      
          	    Stores.jPanel1.remove(Stores.applet);
    	        Stores.applet = new Map();
    	        Stores.applet.init();
    	        Stores.applet.size(400,500);
    	        Stores.jPanel1.add(Stores.applet);
    	        Stores.applet.resize(400,500);
          	      
        		}
        	}
        });
      
 


        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                sel = jTable2.getSelectedRow();

                
            }
        });
	
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                Integer cc = books.get(sel).getCopies();
                Object ss = jTable2.getValueAt(sel, 2);
                textField.setText(ss.toString());
                
            }
        });
        
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	    lblSelectedBookCount = new JLabel();
        lblSelectedBookCount.setText("Selected Book Count");
        
        textField = new JTextField();
		
		jTextField1.setText(s.getName());
		jTextField2.setText(s.getCity());
		jTextField3.setText(s.getCountry());
		jTextField4.setText(s.adress);
		

		
		jLabel1.setText("Store Name");
		
		
		
		jLabel2.setText("City");
		
		
		jLabel3.setText("Country");
		
		
		jLabel4.setText("Address");
		
		jButton1.setText("Add Book");
		
		jButton3.setText("Delete Book");
		
		jButton4.setText("Save");



        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            
            },
            new String [] {
                "Name", "Page number", "Copies number", "Publish Date","Authors"
            }
            
        ));
        jScrollPane2.setViewportView(jTable2);
        
        
   jTable2.getColumn("Authors").setCellRenderer(new ButtonRenderer());
   jTable2.getColumn("Authors").setCellEditor(new ButtonEditor(new JCheckBox()));
   
   model2 = (DefaultTableModel) jTable2.getModel();
	
		   
		   for(BookData bd : books){			 
		       model2.addRow(new Object[]{bd.book.getTitle(),bd.book.getPageCount(),bd.getCopies(),bd.book.getPublishDate()});		
		   }

		  
        
        JLabel lblBooks = new JLabel();
        lblBooks.setFont(new Font("Tahoma", Font.PLAIN, 18));
        lblBooks.setText("Books");
        
        btnOk = new JButton();
        btnOk.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		 
        		 jTable2.setValueAt(textField.getText(), sel, 2);
        		
        	}
        });
        btnOk.setText("Ok");
        
    

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createParallelGroup(Alignment.LEADING)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addGap(55)
        							.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        								.addComponent(jButton4, Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        									.addGap(18)
        									.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
        									.addGap(13))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        									.addGap(18)
        									.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
        									.addGap(13))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        									.addGap(18)
        									.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
        									.addGap(13))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
        									.addGap(18)
        									.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
        									.addGap(13))))
        						.addGroup(layout.createSequentialGroup()
        							.addGap(90)
        							.addComponent(textField, GroupLayout.PREFERRED_SIZE, 132, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, 94, Short.MAX_VALUE)))
        					.addGroup(layout.createSequentialGroup()
        						.addGap(122)
        						.addComponent(btnOk, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
        						.addPreferredGap(ComponentPlacement.RELATED)))
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(lblSelectedBookCount, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        					.addGap(82)))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(69)
        					.addComponent(jButton1)
        					.addGap(141)
        					.addComponent(jButton3))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 499, GroupLayout.PREFERRED_SIZE)))
        			.addGap(29))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(507, Short.MAX_VALUE)
        			.addComponent(lblBooks, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        			.addGap(192))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(17)
        			.addComponent(lblBooks)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel1)
        						.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel2)
        						.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel3)
        						.addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel4)
        						.addComponent(jTextField4, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(28)
        					.addComponent(lblSelectedBookCount)
        					.addGap(18)
        					.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(btnOk))
        				.addGroup(layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, 249, GroupLayout.PREFERRED_SIZE)))
        			.addGap(25)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jButton3))
        			.addGap(27))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store_Edit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Edit_Store = new Store_Edit();
                Edit_Store.setVisible(true);
            }
        });
    }

    public static DefaultTableModel model2;
    private static Store_Edit Edit_Store;
    
    // Variables declaration - do not modify 
 
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private JLabel lblSelectedBookCount;
    private JTextField textField;
    private JButton btnOk;
}


