import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import main_classes.Author;
import main_classes.Book;
import main_classes.BookData;
import main_classes.Store;

import java.util.ArrayList;

import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usama
 */
public class Store_Edit_Add_Book extends javax.swing.JFrame {

	//private Author author = Intro.bd.getAuthorsByName().get(Authors.sel);
	
	
	private Store store = Intro.bd.getStoresByLocation().get(Stores.sel);
	private ArrayList<main_classes.Book> All_Books = Intro.bd.getBooksByName();
	private ArrayList<main_classes.Book> new_Books ;
	private ArrayList<main_classes.Book> Books ;
	
    /**
     * Creates new form Edit_A
     */
    public Store_Edit_Add_Book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
    	
    	new_Books = new ArrayList<>();
    	Books = new ArrayList<>();
    	
    	for(BookData b :store.BooksData){
    		Books.add(b.book);
    	}
    	
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		if(!Books.contains(All_Books.get(all_books_list.getSelectedIndex()))){
        		new_Books.add(All_Books.get(all_books_list.getSelectedIndex()));
        		model.addElement(model2.getElementAt(all_books_list.getSelectedIndex()));
        		}
        		else{
        			JOptionPane.showMessageDialog(null,"This Book is already in yor store Book List");

        		}
        	}
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jButton1.setText("Add Book");
        
        list = new JList();
        list.setModel(new AbstractListModel() {
        	String[] values = new String[] {"a"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });
        
        list_1 = new JList();
        list_1.setModel(new AbstractListModel() {
        	String[] values = new String[] {"b", "c"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });

        
        model = new DefaultListModel<>();
        my_books_list = new JList<>( model );
        

        
         model2 = new DefaultListModel<>();
         all_books_list =  new JList<>( model2 );
        
        
 
        
       for(Book book : All_Books){
        	
        	model2.addElement(book.getTitle());
        }
        
       
       
//      // JScrollPane scrollPane1 = new JScrollPane(list);
//       jScrollPane1.setViewportView(list);
//       jScrollPane1.setViewportView(my_books_list);
       //Author_Edit.add(scrollPane1);
       
        btnNewButton = new JButton("Save");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		int rowCount = Store_Edit.model2.getRowCount();
        		for (int i = rowCount - 1; i >= 0; i--) {
        			Store_Edit.model2.removeRow(i);
        		}
        		
        		for(Book b :new_Books){
            		BookData bd = new BookData(b, 0);
            		Intro.bd.getStoresByLocation().get(Stores.sel).BooksData.add(bd);     		    
        		}
        		
        		for(BookData bd:Intro.bd.getStoresByLocation().get(Stores.sel).BooksData)
            		Store_Edit.model2.addRow(new Object[]{bd.book.getTitle(),bd.book.getPageCount(),bd.getCopies(),bd.book.getPublishDate()});

        	}
        });
        
        btnDelete = new JButton("Delete");
        btnDelete.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new_Books.remove(my_books_list.getSelectedIndex());
        		model.removeElementAt(my_books_list.getSelectedIndex());
        	}
        });
        
        lblAuthorsBooks = new JLabel();
        lblAuthorsBooks.setText("Author's Books");
        
        lblAllBooks = new JLabel();
        lblAllBooks.setText("All Books");
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(122)
        					.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(45)
        					.addComponent(btnNewButton)
        					.addGap(123)
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(lblAuthorsBooks, GroupLayout.PREFERRED_SIZE, 85, GroupLayout.PREFERRED_SIZE)
        						.addComponent(my_books_list, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE))
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(18)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(btnDelete, GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
        							.addGap(28)
        							.addComponent(all_books_list, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE))
        						.addGroup(Alignment.TRAILING, groupLayout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(lblAllBooks, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE)
        							.addGap(11)))))
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(34)
        			.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblAuthorsBooks)
        				.addComponent(lblAllBooks))
        			.addGap(18)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(41)
        					.addComponent(jButton1)
        					.addGap(28)
        					.addComponent(btnDelete))
        				.addGroup(groupLayout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(all_books_list, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)
        					.addComponent(my_books_list, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)))
        			.addGap(6)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(btnNewButton))
        			.addGap(15))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store_Edit_Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store_Edit_Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store_Edit_Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store_Edit_Add_Book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Store_Edit_Add_Book().setVisible(true);
            }
        });
    }

    DefaultListModel<String> model,model2;
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private JList list_1;
    private JList my_books_list;
    private JList all_books_list;
    private JList list;
    private JButton btnNewButton;
    private JButton btnDelete;
    private JLabel lblAuthorsBooks;
    private JLabel lblAllBooks;
}

