///*
// * To change this license header, choose License Headers in Project Properties.
// * To change this template file, choose Tools | Templates
// * and open the template in the editor.
// */
//import javax.swing.GroupLayout.Alignment;
//import javax.swing.LayoutStyle.ComponentPlacement;
//import javax.swing.table.DefaultTableModel;
//
//import main_classes.Author;
//import main_classes.Book;
//import main_classes.BookData;
//
//import javax.swing.DefaultListModel;
//import javax.swing.GroupLayout;
//import javax.swing.JList;
//import javax.swing.JFrame;
//import javax.swing.JLabel;
//import java.awt.event.ActionListener;
//import java.util.ArrayList;
//import java.awt.event.ActionEvent;
//import javax.swing.JButton;
//import javax.swing.AbstractListModel;
//
///**
// *
// * @author Usama
// */
//public class Store_Add extends javax.swing.JFrame {
//
//	private ArrayList<Book> all_books = Intro.bd.getBooksByName();
//	public ArrayList<Book> new_books_array;
//	
//    /**
//     * Creates new form New_Store
//     */
//    public Store_Add() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jLabel1 = new javax.swing.JLabel();
//        jTextField5 = new javax.swing.JTextField();
//        jTextField6 = new javax.swing.JTextField();
//        jLabel6 = new javax.swing.JLabel();
//        jTextField7 = new javax.swing.JTextField();
//        jLabel7 = new javax.swing.JLabel();
//        jTextField8 = new javax.swing.JTextField();
//        jLabel8 = new javax.swing.JLabel();
//        jLabel9 = new javax.swing.JLabel();
//        jButton2 = new javax.swing.JButton();
//        jButton2.addActionListener(new ActionListener() {
//        	public void actionPerformed(ActionEvent arg0) {
//        		new_books_array.add(all_books.get(all_books_list.getSelectedIndex()));
//        		
//        		model.addElement(model2.getElementAt(all_books_list.getSelectedIndex()));
//        	}
//        });
//
//        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
//
//        jLabel1.setText("Store Name");
//
//        jLabel6.setText("City");
//
//        jLabel7.setText("Country");
//        jTextField8.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField8ActionPerformed(evt);
//            }
//        });
//
//        jLabel8.setText("Books");
//
//        jLabel9.setText("Address");
//
//        jButton2.setText("Add");
//        
//        JList list = new JList();
//        list.setModel(new AbstractListModel() {
//        	String[] values = new String[] {"a"};
//        	public int getSize() {
//        		return values.length;
//        	}
//        	public Object getElementAt(int index) {
//        		return values[index];
//        	}
//        });
//        
//        list_1 = new JList();
//        list_1.setModel(new AbstractListModel() {
//        	String[] values = new String[] {"b"};
//        	public int getSize() {
//        		return values.length;
//        	}
//        	public Object getElementAt(int index) {
//        		return values[index];
//        	}
//        });
//        
//        
//        
//        model = new DefaultListModel<>();
//        my_books_list = new JList<>( model );
//        
////        for(Book book : author.books){        	
////        	model.addElement(book.getTitle());
////        }
////        
//         model2 = new DefaultListModel<>();
//         all_books_list =  new JList<>( model2 );
//        
//        
//        
//       for(Book book : all_books){        	
//        	model2.addElement(book.getTitle());
//        }
//        
//	    new_books_array = new ArrayList<>();
//
//      
//        
//        lblAllBooks = new JLabel();
//        lblAllBooks.setText("All Books");
//        
//        btnDelete = new JButton();
//        btnDelete.addActionListener(new ActionListener() {
//        	public void actionPerformed(ActionEvent arg0) {
//        		new_books_array.remove(my_books_list.getSelectedIndex());
//        		
//        		model.removeElementAt(my_books_list.getSelectedIndex());
//        	}
//        });
//        btnDelete.setText("Delete");
//        
//        btnSave = new JButton("Save");
//        btnSave.addActionListener(new ActionListener() {
//        	public void actionPerformed(ActionEvent arg0) {
////	            new_author = new Author("first_name","last_name",null);
////        		
////        		new_author.setFirstName(jTextField1.getText());
////        		new_author.setLastName(jTextField2.getText());
////        		for(Book b:new_books_array)
////        			new_author.addBook(b);
////        			
////        		Intro.bd.addAuthor(new_author);
////
////        		Authors.model = (DefaultTableModel) Authors.jTable1.getModel();
////
////                Authors.model.addRow(new Object[]{new_author.getFirstName(),new_author.getLastName()});
//
//        	}
//        });
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        layout.setHorizontalGroup(
//        	layout.createParallelGroup(Alignment.TRAILING)
//        		.addGroup(layout.createSequentialGroup()
//        			.addGap(11)
//        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
//        				.addGroup(layout.createSequentialGroup()
//        					.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        					.addGap(66))
//        				.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        				.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
//        				.addComponent(jLabel1, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE))
//        			.addGap(54)
//        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
//        				.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
//        					.addComponent(jTextField5, Alignment.LEADING)
//        					.addComponent(jTextField7, Alignment.LEADING)
//        					.addComponent(jTextField6, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
//        				.addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, 122, GroupLayout.PREFERRED_SIZE))
//        			.addGap(62))
//        		.addGroup(Alignment.LEADING, layout.createSequentialGroup()
//        			.addGap(23)
//        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
//        				.addGroup(layout.createSequentialGroup()
//        					.addComponent(list, GroupLayout.PREFERRED_SIZE, 116, GroupLayout.PREFERRED_SIZE)
//        					.addPreferredGap(ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
//        					.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
//        						.addComponent(jButton2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        						.addComponent(btnDelete, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE))
//        					.addGap(26)
//        					.addComponent(list_1, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE))
//        				.addGroup(layout.createSequentialGroup()
//        					.addGap(27)
//        					.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
//        					.addPreferredGap(ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
//        					.addComponent(lblAllBooks, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)))
//        			.addContainerGap())
//        		.addGroup(layout.createSequentialGroup()
//        			.addContainerGap(189, Short.MAX_VALUE)
//        			.addComponent(btnSave)
//        			.addGap(172))
//        );
//        layout.setVerticalGroup(
//        	layout.createParallelGroup(Alignment.LEADING)
//        		.addGroup(layout.createSequentialGroup()
//        			.addGap(38)
//        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
//        				.addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
//        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
//        			.addGap(18)
//        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
//        				.addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
//        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
//        			.addGap(18)
//        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
//        				.addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
//        				.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
//        			.addGap(18)
//        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
//        				.addComponent(jTextField8, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
//        				.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
//        			.addGap(33)
//        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
//        				.addComponent(lblAllBooks, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
//        				.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
//        			.addGap(18)
//        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
//        				.addGroup(layout.createParallelGroup(Alignment.BASELINE)
//        					.addComponent(list_1, GroupLayout.PREFERRED_SIZE, 150, GroupLayout.PREFERRED_SIZE)
//        					.addComponent(list, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
//        				.addGroup(layout.createSequentialGroup()
//        					.addGap(42)
//        					.addComponent(jButton2)
//        					.addGap(18)
//        					.addComponent(btnDelete)
//        					.addPreferredGap(ComponentPlacement.RELATED, 44, GroupLayout.PREFERRED_SIZE)))
//        			.addGap(18)
//        			.addComponent(btnSave)
//        			.addGap(24))
//        );
//        getContentPane().setLayout(layout);
//
//        pack();
//    }// </editor-fold>                        
//
//    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
//        // TODO add your handling code here:
//    }                                           
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Store_Add().setVisible(true);
//            }
//        });
//    }
//    
//    private DefaultListModel<String> model,model2;
//    private BookData new_book_data;
//    private JList my_books_list;
//    private JList all_books_list;
//    
//    private javax.swing.JButton jButton2;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    public javax.swing.JTextField jTextField5;
//    private javax.swing.JTextField jTextField6;
//    private javax.swing.JTextField jTextField7;
//    private javax.swing.JTextField jTextField8;
//    private JList list_1;
//    private JLabel lblAllBooks;
//    private JButton btnDelete;
//    private JButton btnSave;
//}


import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.table.DefaultTableModel;

import main_classes.Author;
import main_classes.Book;
import main_classes.BookData;
import main_classes.Store;

import java.util.ArrayList;

import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JTable;
import javax.swing.JLabel;
import javax.swing.JTextField;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usama
 */
public class Store_Add extends javax.swing.JFrame {

	private ArrayList<Book> all_books = Intro.bd.getBooksByName();
	public ArrayList<Book> new_books_array;
	
    /**
     * Creates new form Edit_A
     */
    public Store_Add() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new_books_array.add(all_books.get(all_books_list.getSelectedIndex()));
        		
        		model.addElement(model2.getElementAt(all_books_list.getSelectedIndex()));
        	
        	}
        });

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        jTextField1.setText("");

        jTextField2.setText("");

        jLabel1.setText("Store's Name");

        jLabel2.setText("City");

        jButton1.setText("Add Book");
        
        list = new JList();
        list.setModel(new AbstractListModel() {
        	String[] values = new String[] {"a"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });
        
        list_1 = new JList();
        list_1.setModel(new AbstractListModel() {
        	String[] values = new String[] {"b", "c"};
        	public int getSize() {
        		return values.length;
        	}
        	public Object getElementAt(int index) {
        		return values[index];
        	}
        });

        
        
        model = new DefaultListModel<>();
        my_books_list = new JList<>( model );
        
//        for(Book book : author.books){        	
//        	model.addElement(book.getTitle());
//        }
//        
         model2 = new DefaultListModel<>();
         all_books_list =  new JList<>( model2 );
        
        
        
       for(Book book : all_books){        	
        	model2.addElement(book.getTitle());
        }
        
	    new_books_array = new ArrayList<>();

      
       
     
       
//      // JScrollPane scrollPane1 = new JScrollPane(list);
//       jScrollPane1.setViewportView(list);
//       jScrollPane1.setViewportView(my_books_list);
       //Author_Edit.add(scrollPane1);
       
        
        
        
        btnNewButton = new JButton("Save");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		
        		if(jTextField1.getText().equals("")||jTextField2.getText().equals("")||textField.getText().equals("")||textField_1.getText().equals("")){
         			JOptionPane.showMessageDialog(null,"Please Fill All Fields");

        		}
        		else{
        		new_store = new Store();
        		new_store.setName(jTextField1.getText());
        		new_store.setCity(jTextField2.getText());
        		new_store.setCountry(textField.getText());
        		new_store.adress = textField_1.getText();
        		new_store.BooksData = new ArrayList<>();
        		
        		for(Book b : new_books_array){
        			BookData bd = new BookData(b,0);
        			new_store.BooksData.add(bd);        			
        		}
        		
        		Intro.bd.addStore(new_store);

        	    Stores.jPanel1.remove(Stores.applet);
    	        Stores.applet = new Map();
    	        Stores.applet.init();
    	        Stores.applet.size(400,500);
    	        Stores.jPanel1.add(Stores.applet);
    	        Stores.applet.resize(400,500);
        		
    	        
        		Stores.model = (DefaultTableModel) Stores.jTable1.getModel();
        		
        		int rowCount = Stores.model.getRowCount();
        		for (int i = rowCount - 1; i >= 0; i--) {
        			Stores.model.removeRow(i);
        		}
        		
        		for(Store store :Intro.bd.getStoresByLocation())
        		Stores.model.addRow(new Object[]{store.getName(),store.getCity(),store.getCountry()});
     		
        		}
    	    
        		
        	}
        });
        
        btnDelete = new JButton("Delete");
        btnDelete.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		new_books_array.remove(my_books_list.getSelectedIndex());
        		
        		model.removeElementAt(my_books_list.getSelectedIndex());
        	}
        });
        
        JLabel lblAuthorBooks = new JLabel();
        lblAuthorBooks.setText("Store's Books");
        
        lblAllBooks = new JLabel();
        lblAllBooks.setText("All Books");
        
        textField = new JTextField();
        textField.setText("");
        
        textField_1 = new JTextField();
        textField_1.setText("");
        
        lblCountry = new JLabel();
        lblCountry.setText("Country");
        
        lblAddress = new JLabel();
        lblAddress.setText("Address");
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(51)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 130, GroupLayout.PREFERRED_SIZE)
        			.addGap(31)
        			.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(51)
        			.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        			.addGap(101)
        			.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(51)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblCountry, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblAddress, GroupLayout.PREFERRED_SIZE, 60, GroupLayout.PREFERRED_SIZE))
        			.addGap(101)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
        				.addComponent(textField, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
        			.addGap(87))
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING, false)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(lblAuthorBooks, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(23)
        					.addComponent(my_books_list, GroupLayout.PREFERRED_SIZE, 94, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(groupLayout.createSequentialGroup()
        									.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        									.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED))
        								.addComponent(btnDelete, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        							.addGap(26))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        							.addGap(34)))
        					.addComponent(all_books_list, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE))
        				.addComponent(lblAllBooks, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE))
        			.addGap(26)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(11)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(10)
        					.addComponent(jLabel1))
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(11)
        					.addComponent(jLabel2))
        				.addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(7)
        			.addGroup(groupLayout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(lblCountry)
        				.addComponent(textField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGap(14)
        					.addComponent(lblAddress))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(textField_1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(22)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblAuthorBooks)
        				.addComponent(lblAllBooks))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        				.addGroup(groupLayout.createSequentialGroup()
        					.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        						.addComponent(all_books_list, GroupLayout.PREFERRED_SIZE, 193, GroupLayout.PREFERRED_SIZE)
        						.addComponent(my_books_list, GroupLayout.PREFERRED_SIZE, 195, GroupLayout.PREFERRED_SIZE)
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(23)
        							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        						.addGroup(groupLayout.createSequentialGroup()
        							.addGap(23)
        							.addGroup(groupLayout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jScrollPane2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jButton1))
        							.addGap(28)
        							.addComponent(btnDelete)))
        					.addContainerGap(82, Short.MAX_VALUE))
        				.addGroup(groupLayout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
        					.addComponent(btnNewButton)
        					.addContainerGap())))
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Store_Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            	Store_Add = new Store_Add();
            	Store_Add.setVisible(true);
            }
        });
    }

    private static Store_Add  Store_Add;
    private DefaultListModel<String> model,model2;
    private Store new_store;
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private JList list_1;
    private JList my_books_list;
    private JList all_books_list;
    private JList list;
    private JButton btnNewButton;
    private JButton btnDelete;
    private JLabel lblAllBooks;
    private JTextField textField;
    private JTextField textField_1;
    private JLabel lblCountry;
    private JLabel lblAddress;
}

